permalink: pretty

url: "https://wipfli.github.io/"
baseurl: ""

maps:
  key: R8rAisQ0L6EL1wW8JVYQ

sass:
  style: :compressed
  sass_dir: maplibre.github.io/style/

exclude:
  - "style/bootstrap/site"
